allowBuilds:
  "@depot/cli": true
  "@sentry/cli": true
  bufferutil: true
  es5-ext: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - '@trigger.dev/build@4.5.10'
  - '@trigger.dev/core@4.5.10'
  - '@trigger.dev/sdk@4.5.10'
